version: 2
updates:
  # Monthly dependency updates
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    labels:
      - pr-priority
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      update-dependencies:
        patterns:
          - "*"
    versioning-strategy: increase
    open-pull-requests-limit: 1

  # Monthly GitHub Actions dependency updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      update-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 1